### ISSUE TITLE
TypeError: null is not an object (evaluating 'data.mdx')

### ISSUE THREAD

**Issue by nathanaelnoir** [janosh/blog#66]
After the development build I'm getting the error:

> TypeError: null is not an object (evaluating 'data.mdx')

After viewing the page local the following syntax is highlighted:

> export default function IndexPage({ data  }) 

which is located in src/pages/index.js.

**Comment by janosh** [comment]
Hmmm... that's odd. Which version of `gatsby` are you using (`yarn list gatsby`)?

Did that happen on the first build? If not, could you try clearing your cache: `gatsby clean && yarn dev`?

If you just remove `src/pages/index.js`, does the site build successfully?

**Comment by nathanaelnoir** [comment]
The versions are the latest ones. If I exclude `src/pages/index.js` the site builds except for the start page, due to the missing index file. Very weird indeed. There must be some conflict with `index.js`.
