### ISSUE TITLE
Problem during gatbsy develop

### ISSUE THREAD

**Issue by JonathanPeterRajan** [janosh/blog#68]
Hi, thank you for this great project!
When running gatsby develop, I get this error 
` - resolve-module-exports.ts:191 resolveModuleExports                                                                    Error: C:\Users\betin\Documents\Blog\blog-master\gatsby-node.js:5291:26                                                     const nextSlug = arr[index - 1]?.frontmatter.slug || ``                                                                                                 ^                                                                                   SyntaxError: Unexpected token '.'strap/load-plugins/validate.ts:193:31 `

**Comment by janosh** [comment]
@JonathanPeterRajan Thanks!

The error looks like it's due to a node version that doesn't support [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Browser_compatibility). It was introduced in v14. Check what `node -v` prints and consider updating if necessary.

**Comment by JonathanPeterRajan** [comment]
Hi, thank you for your quick reply.
I have updated my nodejs to v14 which seems to have solved my initial issue. However, now, when doing gatsby develop I am getting a new error:
`  WorkerError: Processing C:/Users/betin/Documents/Blog/blog-master/content/pages/web/projects/gatsby-paginate/gatsby-paginate.png failed
  Original error:
  'C:\Users\betin\Documents\Blog\blog-master\node_modules\pngquant-bin\vendor\pngquant.exe' is not recognized as an internal or external command, 
  operable program or batch file.`

**Comment by janosh** [comment]
Never seen that error before. Might be Windows-specific. [Someone reported that exact error in the context of Gatsby on Stackoverflow](https://stackoverflow.com/q/61555336/4034025) and apparently fixed it with some `npm install`s.

**Comment by JonathanPeterRajan** [comment]
Thank you, it is all fixed now.
