### ISSUE TITLE
How to make SVG Images

### ISSUE THREAD

**Issue by JonathanPeterRajan** [janosh/blog#71]
Hi Janosh,

I really like the svg title pictures you have made for the blog. An example is 
![image](https://user-images.githubusercontent.com/62900297/91549241-8c476000-e91e-11ea-8ba0-bbf79b4e1787.png)

I would be very grateful to learn how to make something similar myself.

Many Thanks

**Comment by janosh** [comment]
Thanks, glad you like it!

I used [Affinity Designer](https://affinity.serif.com/designer). It's paid software and Mac + Windows only but I heard good things about [Gimp](https://www.gimp.org) as well which runs on every OS and can be used for the same things. I believe Gimp has a steeper learning curve though.

**Comment by JonathanPeterRajan** [comment]
Hi, thanks for the quick reply
I got affinity designer. Is there a specific size/dimensions I need to make the images be?

**Comment by janosh** [comment]
I'm using 2000px x 500px (width x height) and then display the image at full height, letting the viewport crop the image horizontally as necessary. That means you shouldn't place anything important near the left and right boundaries of the image as those will usually not be seen. This is how [Netlify](https://netlify.com) used to do it as well when their landing page still had an SVG wave background.

**Comment by JonathanPeterRajan** [comment]
Thanks a lot for the help!
I just have one last quick question, is there any benefits using SVG over PNG or JPEG?
I see that SVG has a slightly lower file size, but is there any other reason why you prefer to export as SVG?

**Comment by janosh** [comment]
Looks better on high resolution screens. Plus vector images are cool! You can zoom in indefinitely at no loss of quality. SVG FTW. 😄

**Comment by JonathanPeterRajan** [comment]
I see.
Once again thanks for the help👍🙏
