### ISSUE TITLE
Blog Site offline and Gatsby versions bad

### ISSUE THREAD

**Issue by donaldboulton** [janosh/blog#73]
Had the same issues with Gatsby 2.24.73 where if your clear Application storage and update the service worker site goes blank and stay's that way through all links.

And if I go browser back to home page its dead also, same issue I was having before I updated Gatsby to 2.28.0

You removed Gatsby plugin offline and all you needed to do was update it and Gatsby and then get workbox config from CDN to fix it.

And Content-Security-Policy is being looked for and enforced and can cause loading issues in all chromium browsers.

Check out my headers in my netlify.toml file at [netlify.toml](https://github.com/donaldboulton/publiuslogic/blob/master/netlify.toml)

You use different APIs and links than me so update the headers and view console messages for a heads up on missing links and where to put them.

**Comment by janosh** [comment]
Thanks for taking the time to report this. I've stopped working on this site as I plan to rewrite it in Svelte once [`@sveltejs/kit`](https://npmjs.com/package/@sveltejs/kit) releases and I have a quiet weekend.
